create database vendasdejogos;
use vendasdejogos;

CREATE TABLE GAMES (
    NOME varchar(100),
    ANO integer,
    EDITOR VARCHAR(100),
    GENERO VARCHAR(100),
    PLATFORM VARCHAR(10),
  CODVENDAS INT AUTO_INCREMENT PRIMARY KEY 
);

CREATE TABLE VENDAS (
    EUA_VENDAS DOUBLE,
    NA_VENDAS DOUBLE,
    JP_VENDAS DOUBLE,
    OUTRAS_VENDAS DOUBLE,
    VENDAS_GLOBAIS DOUBLE,
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE MERCADO_DE_JOGOS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CODGAMES INT NOT NULL,
  FOREIGN KEY (CODGAMES) REFERENCES GAMES(CODGAMES),
  CODVENDAS INT NOT NULL,
  FOREIGN KEY (CODVENDAS) REFERENCES VENDAS(CODVENDAS),
  CODCLASSIFICACAO INT NOT NULL,
  FOREIGN KEY (CODCLASSIFICACAO) REFERENCES CLASSIFICACAO(CODCLASSIFICACAO),
  CODPLATAFORMA INT NOT NULL,
  FOREIGN KEY (CODPLATAFORMA) REFERENCES PLATAFORMA(CODPLATAFORMA),
  CODNOME INT NOT NULL,
  FOREIGN KEY (CODNOME) REFERENCES NOMEDOSJOGOS(CODNOME)
);


CREATE TABLE CLASSIFICACAO (
    RANK_ INTEGER,
    NOME varchar(100),
    ID INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE PLATAFORMA (
    NOME VARCHAR(10),
    CODPLATAFORMA INT AUTO_INCREMENT PRIMARY KEY
);
 
 CREATE table NOMEDOSJOGOS( 
 NOMES varchar(100),
  CODNOME INT AUTO_INCREMENT PRIMARY KEY
 
 
 
 );

    
    
    
    select * from CLASSIFICACAO;
      select * from GAMES;
      select * FROM vendas;
      SELECT * FROM PLATAFORMA ;
      SELECT * FROM MERCADO_DE_JOGOS;
      select * from NOMEDOSJOGOS;
      
      
    drop table GAMES;
    drop table VENDAS ;
    drop table CLASSIFICACAO;
    drop table  PLATAFORMA;
    drop table MERCADO_DE_JOGOS;
    DROP table NOMEDOSJOGOS;
    show tables; 
    
    
     alter table GAMES drop column CODVENDAS;
    alter table VENDAS drop column ID;
   alter table CLASSIFICACAO drop column ID;
   alter table  PLATAFORMA drop column CODPLATAFORMA;
      alter table  NOMEDOSJOGOS drop column CODNOME;
      
      
    alter table GAMES  add CODGAMES INT AUTO_INCREMENT PRIMARY KEY;
    alter table VENDAS  add CODVENDAS INT AUTO_INCREMENT PRIMARY KEY ;
   alter table CLASSIFICACAO add CODCLASSIFICACAO INT AUTO_INCREMENT PRIMARY KEY ; 
   alter table  PLATAFORMA add CODPLATAFORMA INT AUTO_INCREMENT PRIMARY KEY;
     alter table GAMES  add PLATFORM VARCHAR(10);
     
     
   INSERT INTO MERCADO_DE_JOGOS (CODGAMES, CODVENDAS, CODCLASSIFICACAO, CODPLATAFORMA , CODNOME )
SELECT
  g.CODGAMES,
  v.CODVENDAS,
  c.CODCLASSIFICACAO,
  p.CODPLATAFORMA,
  n.CODNOME
FROM GAMES g
JOIN VENDAS v ON g.CODGAMES = v.CODVENDAS
JOIN CLASSIFICACAO c ON g.CODGAMES = c.CODCLASSIFICACAO
JOIN NOMEDOSJOGOS n ON g.CODGAMES = n.CODNOME
JOIN PLATAFORMA p ON g.CODGAMES = p.CODPLATAFORMA;


delete p1 from PLATAFORMA as p1
join PLATAFORMA as p2
 on p1.nome = p2.nome
 where p1.CODPLATAFORMA > P2.CODPLATAFORMA;

delete p1 from NOMEDOSJOGOS as p1 join NOMEDOSJOGOS as p2 on p1.nomes = p2.nomes  where p1.CODNOME > P2.CODNOME;

   DELETE p1
FROM NOMEDOSJOGOS AS p1
JOIN (
    SELECT nomes, COUNT(*) AS qtde_nomes
    FROM NOMEDOSJOGOS
    GROUP BY nomes
) AS p2
ON p1.nomes = p2.nomes
WHERE p2.qtde_nomes > 1;
   
  